### ISSUE TITLE
Error in check_twitter_oauth() : OAuth authentication error: This most likely means that you have incorrectly called setup_twitter_oauth()'

### ISSUE THREAD

**Issue by karanbgsr** [geoffjentry/twitteR#95] opened 2015-07-27 17:27 UTC
Have done everything

1. Created a new app
2. Made all the changes to call back url
3. install_version("httr", version="0.6.0", repos="http://cran.us.r-project.org")
4.setup_twitter_oauth(consumer_key = "***",
                    consumer_secret ="******"
                    ,access_token = "***-******",
                    access_secret = "****")
nothing is working...help!!!!

**Comment by karanbgsr** [comment] 2015-07-27 17:32
tried this also..

download.file(url="http://curl.haxx.se/ca/cacert.pem",destfile="cancert.pem")

requestURL<-"https://api.twitter.com/oauth/request_token"
accessURL<-"https://api.twitter.com/oauth/access_token"
authURL<-"https://api.twitter.com/oauth/authorize"
consumerKey<-"*************"
consumerSecret<-"************"
cred<-OAuthFactory$new(consumerKey=consumerKey,
                       consumerSecret=consumerSecret,
                       requestURL=requestURL,
                       accessURL=accessURL,
                       authURL=authURL)
registerTwitterOAuth(cred)
cred$handshake(cainfo=system.file("CurlSSL","cacert.pem",package="RCurl")
install_github("twitteR", username="geoffjentry")
install_github("jrowen/twitteR", ref = "oauth_httr_1_0")

**Comment by geoffjentry** [comment] 2015-07-29 13:27
Duplicate of #90 - please see that issue.

**Closed by geoffjentry** 2015-07-29 13:27 UTC
