### ISSUE TITLE
setup_twitter_oauth stopped working

### ISSUE THREAD

**Issue by neuwirthe** [geoffjentry/twitteR#91] opened 2015-07-06 14:04 UTC
Until about 2 weeks, setup_twitter_auth worked nicely with my keys and tokens.
Now, whenever I try, I get an error:
[1] "Using direct authentication"
Error during wrapup: OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'
I also created a new up with full access (read, write, direct messages), and twitteR is not
able to connect to the new app.
Is this a new problem? What can I do about it?

**Comment by neuwirthe** [comment] 2015-07-06 14:14
When I try with only consumer_key and consumer_secret, I get

[1] "Using browser based authentication"
Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

Selection: 2
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission) : 
  client error: (401) Unauthorized
>

**Comment by jrowen** [comment] 2015-07-06 19:04
Try setting the Callback URL for your [app](https://apps.twitter.com) to `http://127.0.0.1:1410`.

**Comment by geoffjentry** [comment] 2015-07-07 12:18
See #90

**Comment by geoffjentry** [comment] 2015-07-07 12:18
Closing as this is a duplicate of #90

**Closed by geoffjentry** 2015-07-07 12:19 UTC

**Comment by neuwirthe** [comment] 2015-07-07 12:54
Setting the callback URL did not sove the problem.
Going back to httr version 0.6.0 solved the problem.

I will check your github site to see when the problem is solved with the new version of httr also.

Thanks for your help.
